### ISSUE TITLE
LECO director modules

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_plugins_mock#30]
Where should the the LECO director modules reside?
The TCP modules reside in the main pymodaq repository and this package only imports them from pymodaq.

Right now, the move module resides in this repository, while the viewer modules just import the generic viewer module from pymodaq.

Therefore,
- either the move module should be in pymodaq itself and only imported here,
- or the generic viewer module should move into this repository as well.

I'm for having all director modules in the pymodaq repository, where the corresponding actor modules reside, such that they correspond always to each other.
This repository should only import the pymodaq modules, in my opinion.

**Comment by seb5g** [comment]
The base class should be in the pymodaq repository while the actual instrument plugin clss should reside in the pymodaq_plugins_mock repo. This is the same as with the TCPServer plugins

https://github.com/PyMoDAQ/pymodaq_plugins_mock/tree/feature/pyleco-directors

For ease of handling, the best is to have a base/generic director class in pymodaq that would be imported into pymodaq_plugins_mock:

![image](https://github.com/PyMoDAQ/pymodaq_plugins_mock/assets/6609955/524e2c0a-1391-40db-bdea-ae6ea27d2587)

**Comment by BenediktBurger** [comment]
Ok, then my PRs do the right thing: Move the base class to pymodaq and change the file in the mock_plugins to import the class defined in pymodaq.

**Comment by seb5g** [comment]
yes it does! I merged them :-)

**Comment by BenediktBurger** [comment]
One PR remains to be merged: The one, which adds the file to pymodaq itself

**Comment by seb5g** [comment]
done

**Comment by BenediktBurger** [comment]
The move_LECODirector module has been moved to pymodaq while keeping a _starter_ in mock_plugins.
