### ISSUE TITLE
Starting the Coordinator

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/pymodaq_plugins_mock#31]
Thanks for hinting at running the coordinator module here:

https://github.com/PyMoDAQ/pymodaq_plugins_mock/blob/1b7eaeedf31a7bd1cd7a2ba43b651234fd98d7dd/src/pymodaq_plugins_mock/daq_move_plugins/daq_move_LECODirector.py#L6

I did not know, that that works. Thanks.

In order to simplify starting the Coordinator (and other services), I added the Coordinator to the installed tasks similar to the pymodaq dashboard.
Now you can execute `coordinator` in the terminal and it will start as well.

Just as an information.

**Comment by seb5g** [comment]
Ok that will do!

I think we also should have a menu entry in the dashboard allowing to start the coordinator. in the code, we could do that using a subprocess. Do you know how it works? If no, I can do it! Moreover during pymodaq initialization and given a config parameter value (`start_leco_coordinator` boolean for instance) one could start it there

Seb

**Comment by BenediktBurger** [comment]
> I think we also should have a menu entry in the dashboard allowing to start the coordinator

Yes, that is, what I proposed in the leco-test PR

> in the code, we could do that using a subprocess. Do you know how it works? If no, I can do it! Moreover during pymodaq initialization and given a config parameter value (start_leco_coordinator boolean for instance) one could start it there

I don't know (yet) the dashboard, so I'd prefer you to do it.

**Comment by BenediktBurger** [comment]
> However we have an issue with the testing, pyleco is only available for python >= 3.9. This make my CI fail for python == 3.8
Do you have an idea on how to solve this?

I tried to make pyleco compatible with Python 3.8, but my dependency requires Python 3.9...

**Comment by seb5g** [comment]
can we mark the tests needing pyleco to run only if python >=3.9

**Comment by seb5g** [comment]
hum sorry, obviously you did it in the leco repo...

**Comment by seb5g** [comment]
is there a way to check if a coordinator is already running? In order to not start it twice (startup and in dashboard)

**Comment by BenediktBurger** [comment]
> can we mark the tests needing pyleco to run only if python >=3.9

Yes

> is there a way to check if a coordinator is already running? In order to not start it twice (startup and in dashboard)

You could check, whether you can connect to a Coordinator:
~~~python
from pyleco.directors.director import Director

with Director(actor="COORDINATOR") as director:
    if director.communicator.namespace is None:
        start_coordinator()
~~~
- `start_coordinator` is your method starting it
- The Director creates a Communicator, which tries to sign in.
  - If the sign in is successful, the namespace is not None anymore.
  - If not, you start a new coordinator.

**Comment by seb5g** [comment]
@BenediktBurger could you check the way the coordinator is now started in the __init__ of pymodaq is doing it properly? and close the issue if yes!

**Comment by BenediktBurger** [comment]
I just verified it. It works.
